translate/urls.py
from django.urls import path
from . import views

app_name = "translate"
urlpatterns = [
  path("create/", views.TranslateCreateView.as_view(),name="create"),
  path("", views.TranslateListView.as_view(),name="list"),
  path("<str:pk>/", views.TranslateDetailView.as_view(),name="detail"),
]

translate_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("translate.urls")),
]

translate/models.py
from django.db import models
import os

class Translate(models.Model):
  text = models.TextField(max_length=1000)
  translated_text = models.TextField(max_length=1000)

translate/views.py
from django.views import generic 
from django.urls import reverse_lazy
from boto3 import Session
from .models import Translate
from django.core.files.base import ContentFile

class TranslateListView(generic.ListView):
  model = Translate
  template_name = 'translate/list.html'

class TranslateDetailView(generic.DetailView):
  model = Translate
  template_name = 'translate/detail.html'

class TranslateCreateView(generic.CreateView):
  model = Translate
  template_name = 'translate/create.html'
  success_url = reverse_lazy('translate:list')
  fields = ['text']
  
  def form_valid(self, form):
    translate = form.save(commit=False)
    response = use_translate(translate.text)
    if "TranslatedText" in response:
        translate.translated_text = response["TranslatedText"]
    translate.save()
    return super().form_valid(form)

def use_translate(text):

    # create session
    session = Session(profile_name="default")
    translate = session.client("translate")

    # create translation data
    response = translate.translate_text(
                Text = text,
                SourceLanguageCode='ja',
                TargetLanguageCode='en'
                )

    return response

translate/templates/translate/create.html
<!DOCTYPE html>
<html>
  <header>
    <title>翻訳作成ページ</title>
  </header>
  <body>
    <div>テキスト情報を入力してください</div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">翻訳</button> 
    </form>
  <body>
</html>

translate/templates/translate/detail.html
<!DOCTYPE html>
<html>
  <header>
    <title>{{ object.text }}</title>
  </header>
  <body>
    <p>{{ object.text }}</p>
    <p>{{ object.translated_text }}</p>
    
  <body>
</html>

translate/templates/translate/list.html
{% for translate in object_list %}
<p>
  <a href="{% url 'translate:detail' translate.pk %}">{{ translate.text }} </a>
</p>
{% empty %}
テキストがありません
{% endfor %}

<div><a href="{% url 'translate:create' %}">テキストを作成する</a></div>